language: node_js
sudo: required
node_js:
- '10'
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
  - node_modules
stages:
- test
install:
- npm ci
before_script:
- npm install -g cordova ionic
- ionic cordova platform add browser
- npm run build:browser
script:
- npm run test:ci
addons:
  artifacts:
    s3_region: us-west-2
env:
  global:
  - ARTIFACTS_BUCKET=mymsafety
  - ARTIFACTS_PATHS="./logs:./cypress:/var/log"
  - secure: BBufr1PalURwgHiuNAgfCat6jdBn1IjetiDEd8fnZvk2bIgIFRaj5xh3+HtB6uzorsa+51dhXtuO3VQrlvS0jo3eO/1cbixsJg6jRiRtDTlgwcOgsLixwRIeX+28aw/1LthhVhWMdUIF0eBn2J4VlJ7an7JNOH30Zmx8zZywEn+oIA5M3dc67QmASkR8NHMqDyiJ+2i32mnydtdRK9IPdL0Hgf9VWN0lh4cLYxDjuI9igtZIzw6VGwz+7Aev6vWy2pcRnJTjYZM3R+mdhiPQYAQ399gqfG0AraT3RuDsIuENrlSJY+wPH9EyAojZaRU0h/y+ZxGSt86qVHnLbZBPR4+mFVZCWFqerCXYcOpnxeH6/EOqlqO4y8AyWh9rSdeF03OemuEmNiwFttKZnmBTJ/WQeeuhAs2DUENSjIwJ4sAep6zCdTn3StkbWobdv8w1P1cIQiTIymm+mBpxEzGWEcrxsvA1QZn2ySwKblMYg21KbEjuI5Zbf2uoNA8KnMaBSoHFdRMxhZY0gMxeU9oPiQ6Jh7OIdWNr3kcsf0rgE37KRIKjJ3wRxnFmZGhCml6rusN+2PvoceIqQX//QKr+NAX7YhP7v3oJhMB5H4bSIhaJzXsSXP/j87JIVsBVxZr3zJWUI4xQSPBeD1RL4GpeG1VGHgMo/LcglA+50pDug6I=
  - secure: TbKA2yQgBgIt75I4Op3MsUA/BBqDRSG1zNGgSKQIz9W/0p0DDVlOdkm4rPQ63Y0RCjvfaJU3tKfLDDhRCTGdjbEzVa8hUTGSXlj/KiN8xlk61bBLLeo+HsxZU5uj5UprDi0D7cldfLYwzw45GU160LUkEiMG5dL0Y0FZFQFjEPs1G8r/TMT9AfswbE9fj4Xz2QTQEsRvt2SyXBQ3zeE38CbxKld+hq/OKDSYkQzbKfhyKgHDX9BNNoiqSINnVOzmMqMHbBf0h14/d3L1Tum1Jvgk7euIRhSSVasBiIJ8aCBX1YYvCxV86WTcAkj0LCYTVQH9XY4PsMWsalY0ayJg01Taq+OIG2qlc+eos8514ybQZNmg2UnCCB7uIkEGhGh6j8anuADQnf222DnpAJR1cRD9pCOOioCyidCA/jq7x5SW5HEORRmH6aeHo++DVcYGPNZK1DTgcNhDJJOADuzq3/aa4LRW/vbc55xLUeUeffJUy/B2YYeAh8yNVmVWyPQwPjBQ7jAW7UMaR1eqeVfSeZpJglt7hkJWR0ZVURB5YKpr9GECchzL+QQnYWNfK5Xufkq7vyUzllAWrM256QrdtR8HssFyLp49LVKyPT0fH1vK3xCzQAbGSghLfAp19Jw2Y2du4PlFEp2OH5Q2gPiPgS+HuikOVMK4Fu4gL/Iqp5s=
