language: node_js
sudo: required
node_js:
- '10'
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
  - node_modules
stages:
- test
install:
- npm ci
before_script:
- pip install --user awscli
- aws s3 sync s3://mymsafety/cypress cypress
- npm install -g cordova ionic
- ionic cordova platform add browser
- npm run build:browser
script:
- npm run test:ci
addons:
  artifacts:
    s3_region: us-west-2
    debug: true
after_success:
  - aws s3 sync cypress s3://mymsafety/cypress
env:  
- ARTIFACTS_BUCKET=mymsafety
- ARTIFACTS_PATHS="./cypress/screenshots:./cypress/videos"
- secure: JBLrXqkK7TQ/cFVDSd8axPf8LEQ25LL0jyqlSNP59/9ImrB7kJUmvo0PJEE2b+wHTJYWKhRapiSTHzfUiewAf3htJTRIsfZIQ70FwNYSZCY1z/Cn34SAuTYwYRDNTWUn0eIlxgXjWy+uwVBA8sGrTXU0iLjvnrs3gkNSeGG9XQoGxZCBufy6VtBmNOrgKX6TC/8+JLP6TSfGt3RdQrEeVYDY3HJvKttdBMbagXFVBqzPbf0MqIkQq9N2clIGzFpcaLwMdNbsj1IBN3Tgm6zaushdDSBert77t237kaLuaUvNE7XjSVhTLmZCrqzjfQoirYuHv9oWU8FUGWiu9pIQG5k9s3zi403lSI6Byuofg+f4bDTU3wkJmVbZrSFvL5kJJUzvk0AucMvk19sQFMsNxRkRkZMQkTrn/QK0W4GSBGINesf4iDy9gC8PTf+zNvPgiTThOIjUYXczY5uclPpZzGQeqddXgL85sofru8SI0xOZeavKOMSFeEjC4OjB/gDUjH2PKZCskKuwGKgv3QOyGcSI3vtTwcV8qAVv3pkzKCpIdEkPU3KtcBBdLkVKjIr9aoOWp5qgpcWkqyOQ+7QE0OByXtZlbeS3Q52YkKo0Znz0nEZ2v+1cVWTa2FYQB8bqGjLcuxA/kNjDB5SO4qBYKgSYAqG4z9a7Umxr//tjTE0=
- secure: CTN7KlFrOGAyxieK+bklw2Je4ntiO+XIc1X+5nQ0tI8N7Kms3yA2r8d09hKbBY6Jez1Qu5rtoar3q7B6JbQBNlVqyckmAkjIzPlm38eoGTapT//SUYMmCxo/KI5s8dUSfOY0SrDnef39uxmNA30ra/Gm+RcSFBst0kHlLOeGU2WqaZMnjQB/FTSx/GNCuUi4QewcZHrSOWwANFusvBbkvgZzUKgxiTdprsxj8Qyq+HmjvrYGC400xM3bV49QzVgc92FGsBkl8wUf6WSdkEZ/4xRIXujJU4o5EffKxEBC2C0vsKlm9cO39Bu6DV3wEY1Mv0/J/VqCnEGIY5gRx6pEc3os+UscWzkLmb6X/5TzjtcxHgBuFoDhD0Bc4ZJ/f2pW0EqyCvLTFDf8ktuBmuv4BJCC231PqK/gbNgZpfynueVqmHge6dtAAmFlmp7521utiOB98CLIAq5SSnnE4BULuU1Ik5XFgFkoIeGqNLogrAJBRipIZYM6Bm+LkE8f8Ve+h3p9mllvNxZG+gNMxa7jxYiITR/CgLETV+egbxuFFMH+smA+MLLDRoDAH3Q551CQLFGNUNVfY8/D0Dz09oGjD/frokYy4VereOkHNphSjf4qy1TwZ1wGSVE9gK7hG2FzFv9ievzolr24cjthkK2HgQtGjUCPoDqEr+FHK15U5hU=
