language: node_js
sudo: required
node_js:
- '10'
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
  - node_modules
stages:
- test
install:
- npm ci
before_script:
- pip install --user awscli
- npm install -g cordova ionic
- ionic cordova platform add browser
- npm run build:browser
script:
- npm run test:ci
addons:
  artifacts:
    s3_region: us-west-1
    debug: true
after_success:
- aws s3 cp cypress/videos s3://mymsafety/travis/travis/$TRAVIS_BUILD_NUMBER --recursive
- aws s3 cp cypress/screenshots s3://mymsafety/travis/$TRAVIS_BUILD_NUMBER --recursive
env:
  global:
  - ARTIFACTS_BUCKET=mymsafety
  - ARTIFACTS_PATHS="./cypress/screenshots:./cypress/videos"
  - secure: MNj8fCD5+pw/BdnDqeLlBGLemYa/EYxtaKTchWGADLj1u8BHq9kS9zRBmCvlNOzcvV0jPwYqvZXPeLCLoFskBuxDibhTXpiV0Rhr7/Tw5rekj6RnjabAKFWh2nD3OCUzQMejr79YFK2tL5rsu1u8KWXJvS2DEsoII4qF8QKOnCZHL7pZ3ouwXjATdw45gdGdunjbHgy6viT8zSmIEfrHJFFILUim4LVZuG8zUNX0i46fKPDnN0QzL/ZxIqqKyXRBP7nEYjtqBViBQrxD1oN4YH2mgOlVZdrUe8t0gOFDVMvwAhtiKiHX67fwUSaz8oq2ra/KfJ1pLFwN+7Pvq37l2cbXESGSAW/hkBtYJ4PYippvqNhaPua2KqmHBWKUNXjRluwoBE4ZgYk6kASrOvZj1WeccCtzBmUizDb2brX+MhaQfxcBRmKMD6l6R++eoxWcIzBTzzB1TB93250PjWaR6WpBc2wih5YOmeohbVLXvcwaMX1ofBYb/jukTFYOxW/3MsxLx1PJugLL4Qq0pI69RePSg6r8a8CkWOo93hEdwoDtD8bxRCl54CXzGCyXzBq3hdF3xKBnGJ/jCfu1aEypPuryuOo9PBOrQKpW3WTW2uY+KH4l8/8PECW23O1k8UTWeY8Q1gWnMAO91WS3QO9c0LwBq69Qa7tYmJ3ZnC7UNkg=
  - secure: ImZGd/ppgGZdNqJ8dFhxPBNSGh5qmEitDvZGTfrNYKtAu+FdviqM/wRGZXjnmJcxkdJ/e/OiM2KAcMBAsS7wMkrsGSHbOwPfQnrqnjtwh3QoBzuQ7uNIMI4cz5mTBq2fiXoQ7RRtH9SrBTiSe6ycmxDy/licqFAVsxngonvGMKttgb5R3QhfMEE7cydxCUK82AibIb9rho0gAs6KyFgTDnCAfp191OV1zljvyk4as1+oIQokhujq0Y2tFCS5GJRbCCtk8K7F0+Hs1IegfO76lBmmgHOxYNcpG5/AmdmM5IdauGoS/OHmKxbN+nroZKCnivKRCpPSZyVp8JEIorNWxx8z+0mbuw9JA1CoGxOwsneWkHz/9JheqDVdV9DS4Di9iGZVxW8Oa7eVFSgoqpLxa9b29c926/QujHs9K9gD7VSc8MidrKhzjAl9fXJakibbDWkMrbqZ2vQXXF4UAfPuoaQgnbdUVzGfKeKQCjlPzNeFFu5M1FDZdPMWqLncE/xOFrwyb2rCv7tv4Py3Mk5Fy223Tf2gfEWsinQa5L0hq0HM0mA7X/LB3jVkPcmo0P9wIJnb+QlaNwgUFUW/3PKn1GPJZMzlLxRAbqCfQlp0piJQiOm9Wr/ycITfiBJDlU9UkREZj5aTld+h1XfAxDthnA8c5s0xb7hZj1bFQ5MrU2A=
  - secure: VnD7PzD1ZvcW52B83zGhG+BQuP7CCimYkK7tnZvQkHueoaV5hz2UnvqFxXkbx05AoBZYke8WgTmsRbbe2xQiJcmdoDZvpewYvFVOQgSaqi8KVhecn6SuhjxYSDB8mzkGeyjcEdnSYmE6WT+r5LEESZAeOKJ+2peaeTLZc3CURYhMoXlIovkfsX1oAVLDVo/v8/NBb9zCllTjTRK+DpvguiLe2KlG3tZy+PfhzdYtWRAQBNmqbTyDQyf4LR/WNEAZMexPfJS3cGG9taRhYSUIp2L78T5slWYr4erNcEY6mWBpIDXQwXyjnoIpZktsZsaw0gfXPmX7onjclWn1AMWk31hWgiQOEI3fAl/W3sk3WFUXGPHvLF9LufNJnF63Trlm1IM1j3nz18r19trVnG8ScYCBeX5g3hVlvpgXk82+4N/qJuEUW4ambMz/krbi+3DW63mi0fCOBsTVCPgMoZRgaLfvhKu9nTGVyrj7wNyBiEBauCAbXiHIbGYYXCcrDOOhqYcBMh2/Si4EWrtwov2wKy90Y8e/kUHPxW5DY6zrI4IZvrvZMzEvY/p2e/KD2f0eEtpaH1+lJCkQyZq7BVk0mALej27AUQHsg64+E1tvOoRqQNNJADiyjUBhw5j+41wHlvu4ByQiLe8TtsfQhHL4BGyxCZDmieSdPj4B64ZU8Ks=
  - secure: QTC/AIhZWuxwC/xw9/fdm9ctFBGDP/JLOMgX0brthG0N/ArWFgxbhLsYyYdUgbmbp+PQmF1+Es3VpTzlFWV8w2HkaJXvkOopx7iF5i2imsSL25GmQlPXxWn1Ie2gMeWWYQ10myVCNzx9l4xnn9vswJfuFEWqNgi50mq2kPIr1dXMSSgWwWSjgPlYIIG7iKOpwbC3vv2zweiIDsBhBhmXUk+s3bQVrC/go13QvyRaDeiNSid/jASbK8qxK05xUVbTYm3EWC4hlvpaFZ4xUIlO+Dj/DMOezsXAjS1bwmw8pV2ndJ5SR/vo97LfCb3rbqnGxCO0Kl0dFy8GcuHh0eycT4Nrz53KEfADTmjnimZ3MbGQK+PhqDxDiGsmlGrnkrq9pQWpMQngQY2Dqlzgj7FZ8hgc8VHQEEouc+S2gnM5f4bM6CxbfJtPSsWJu6Y9JJha+AMF01ZNgqFtM1yHErmlMhYSt4ymEK5mZu9C3Ia9fCTP1pcbYI5UW4U6a4l1IKwZ/EsGjhTvaqdUgGNW+yP5V+yZmpNUAOPyZFskVeo2u25XRSH31HGXN2Lp0cYDyM96ITjST74zxkr5jv8RifIG182meCYIxQIPo+sfEKEtw5sPiVe0k3OBX0j0XZWD68codm5oXhpQmYDJhHAI8YD9RX1aDW3UK1lAQj4jR8z/jCk=
