language: node_js
sudo: required
node_js:
- '10'
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
  - node_modules
stages:
- test
install:
- npm ci
before_script:
- npm install -g cordova ionic
- ionic cordova platform add browser
- npm run build:browser
script:
- npm run test:ci
addons:
  artifacts: true
deploy:
  provider: s3
  access_key_id: AKIAI65OPKVPMMHGHMVQ
  secret_access_key:
    secure: TUloxqpJ5hXtx1FfOFQoqiGS7qSfbGdoMdycoT+yorUgoH86FqUTblCqFN9CNdbCY5OPSEUPUsvU/SrtDN/bhCJoYNKKKQ53elPLzg0/g5n+Ryn+ul5l5NMN43ykB+OGFv6SFmUPpkCM2FGtK5qIaawlAsLob/r3IGZxbno6LqcccHC7bXjCXkdh15CUnPItXjyTLwjpCiufOo4DZ7uqrMqN+NEtTWcV6OJmfqrjKTZ4l7jALC9rnCGm2iDCrfU/1BhGbx95JswoarzBeMMkloNs6dPSJTlHB8JMNWhDvsR9iD7NYUPUva37URK5G1NOJkLhyZT3VmOjNg3RmoZW6zDF7TOST4V9SgnF7utQosox4qoaRAtXxVdWouaJlbxiTuOs9ymm/U5ypNFHKRombKL+4Gz6wVrjgGOAPWTPYHvP5c/nkMhsJSmcAZ3MoXEOyXICrBQgAOFnEGny3a6WGFwMi8HQJmjxLNPkYAZ6qu9Mn3qshacqph0YMeC0Tf1V44pdPA0jGjy3RM/g65INK4a5mxsLCn//F9/MTfTXXVVybr0+/WYgYljTbwmbF5OYBzzjT8O/jQP4uv+ClSbMVO2B4PjDyKaQe7PGmH8ePWSuhpNz/CbXcX83s1ercfm7dVWSTFYLB6a0zigw32kMloAL05CHRDTjav1T1dnTs7s=
  bucket: mymsafety
  local-dir: cypress/fixtures
  upload-dir: cypress
  acl: public_read_write
  on:
    repo: altixco/ionic-cypress
    branch: travis_s3
